version: 2

models:
  - name: daily_customer_metrics
    description: "Daily aggregated customer metrics"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_id
            - day_time
    columns:
      - name: customer_id
        description: "The unique identifier for a customer"
        tests:
          - not_null
          - relationships:
              to: ref('stg_transactions')
              field: customer_id

      - name: day_time
        description: "The date of the aggregation"
        tests:
          - not_null

      - name: protocol_fee_amount
        description: "Cumulative protocol fees for the customer up to this date"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true